## 예외 처리
### 예외란?
- 프로그램 실행 중 발생하는 예기치 않은 상황

### 예외 처리의 필요성과 장점
- 프로그램을 안정적으로 유지하는 데 도움을 줌
- 프로그램 안정성, 디버깅 용이함 ↑

### 예외처리 구현
- try-catch 블록을 사용하여 구현
  - __try__ : 예외가 발생할 수 있는 코드를 작성
  - __catch__ : 예외 처리
  ```cs
  try
  {
    // 예외가 발생할 수 있는 코드
  }
  catch (ExceptionType1 ex)
  {
    // ExceptionType1에 해당하는 예외 처리
  }
  catch (ExceptionType2 ex)
  {
    // ExceptionType2에 해당하는 예외 처리
  }
  finally
  {
    // 예외 발생 여부와 관계없이 항상 실행되는 코드
  }
  ```
- catch 블록의 우선순위
  - 위에서부터 순서대로 실행
  - 예외 타입에 해당하는 첫 번째 catch 블록이 실행됨
  - 예외 타입이 상속 관계에 있는 경우 상위 예외 타입의 catch 블록 먼저 실행

- 다중 catch 블록
  - 다양한 예외 타입 처리 가능
  
- 예외 객체
  - catch 블록에서는 예외 객체를 사용하여 예외에 대한 정보 액세스 가능

### finally
- 예외 발생 여부와 관계없이 항상 실행되는 코드
- 예외 발생 시 정리 작업이나 리소스 해제 등의 코드가 포함될 수 있음
- 생략 가능
- 실행 시점
  - 예외 발생 : 예외 처리 과정 후 finally 실행
  - 예외 발생 X : 앞 과정 후 실행

### 사용자 정의 예외 처리
- __Exception__ 클래스를 상속받아 작성

### 예제
```cs
try
{
  int result = 10 / 0;	// ArithmeticException 발생
  Console.WriteLine("결과 : " + result);
}
catch (DivideByZeroException ex)
{
  Console.WriteLine("0으로 나눌 수 없습니다.");
}
catch (Exception ex)
{
  Console.WriteLine("예외가 발생했습니다 : " + ex.Message);
}
finally
{
  Console.WriteLine("finally 블록이 실행되었습니다.");
}
```

- 사용자 정의 예외 처리
  ```cs
  public class NegativeNumberException : Exception
  {
    // 부모에게 message를 전달해서 먼저 실행 후 내가 정의한 예외 처리를 실행
    public NegativeNumberException(string message) : base(message) 
    {
    
    }
  }
  
  try
  {
    int number = -10;
    if (number < 0)
    {
      throw new NegativeNumberException("음수는 처리할 수 없습니다.");
    
    }
  }
  catch (NegativeNumberException ex)
  {
    Console.WriteLine(ex.Message);
  }
  catch (Exception ex)
  {
    Console.WriteLine("예외가 발생했습니다 : " + ex.Message);
  }
  ```
  ```cs
  // 플레이어 이동
  try
  {
    // 플레이어 이동 코드
    if (IsPlayerCollidingWithWall())
    {
      throw new CollisionException("플레이어가 벽에 충돌했습니다.");
    }
  }
  catch (CollisionException ex)
  {
    // 충돌 예외 처리
    Debug.Log(ex.Message);
    ...
  }
  ```
  ```cs
  // 리소스 로딩
  try
  {
    // 리소스 로딩 코드
    LoadResource("image.png");
  }
  catch (ResourceNotFoundException ex)
  {
    // 리소스가 없는 경우 예외 처리
    Debug.Log(ex.Message);
    ...
  }
  catch (ResourceLoadException ex)
  {
    // 리소스 로딩 중 오류 발생한 경우 예외 처리
    Debug.Log(ex.Message);
    ...
  }
  ```
  ```cs
  // 게임 상태 전이
  try
  {
    // 상태 전이 코드
    if (currentGameState != GameState.Playing)
    {
      throw new InvalidStateException("게임 실행 중이 아닙니다!");
    }
  }
  catch (InvalidStateException ex)
  {
    // 상태 예외 처리
    Debug.Log(ex.Message);
    ...
  }
  ```